name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GCP_FOLDER_ID: ${{ secrets.GCP_FOLDER_ID }}
  APK_PATH: build/app/outputs/flutter-apk/app-debug.apk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Run Flutter Analyzer
        run: flutter analyze

      - name: Build APK
        run: flutter build apk --debug

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.4'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/scripts/requirements.txt

      - name: Decode GCP service account key
        run: echo "$GCP_CREDENTIALS_JSON" | base64 --decode > .github/scripts/gcp-key.json

      - name: Upload APK to Google Drive
        run: python .github/scripts/upload_to_drive.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: .github/scripts/gcp-key.json
          GCP_FOLDER_ID: ${{ secrets.GCP_FOLDER_ID }}
          APK_PATH: build/app/outputs/flutter-apk/app-debug.apk
