name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Run Flutter Analyzer
        run: flutter analyze

      - name: Build APK
        run: flutter build apk --debug

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create directory for GCP key
        run: mkdir -p secrets

      - name: Decode GCP service account key
        run: |
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" | base64 --decode > secrets/gcp-key.json

      - name: Verify JSON key file
        run: |
          echo "Contents of secrets directory:"
          ls -al secrets
          echo "Contents of gcp-key.json:"
          cat secrets/gcp-key.json

      - name: Upload APK to Google Drive
        run: python upload_to_drive.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: secrets/gcp-key.json
