name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Run Flutter Analyzer
        run: flutter analyze

      - name: Build APK
        run: flutter build apk --debug

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create GCP service account key file
        run: |
          echo '{
            "type": "${{ secrets.GCP_TYPE }}",
            "project_id": "${{ secrets.GCP_PROJECT_ID }}",
            "private_key_id": "${{ secrets.GCP_PRIVATE_KEY_ID }}",
            "private_key": "${{ secrets.GCP_PRIVATE_KEY }}",
            "client_email": "${{ secrets.GCP_CLIENT_EMAIL }}",
            "client_id": "${{ secrets.GCP_CLIENT_ID }}",
            "auth_uri": "${{ secrets.GCP_AUTH_URI }}",
            "token_uri": "${{ secrets.GCP_TOKEN_URI }}",
            "auth_provider_x509_cert_url": "${{ secrets.GCP_AUTH_PROVIDER_X509_CERT_URL }}",
            "client_x509_cert_url": "${{ secrets.GCP_CLIENT_X509_CERT_URL }}",
            "universe_domain": "${{ secrets.GCP_UNIVERSE_DOMAIN }}"
          }' > $HOME/gcp-key.json

      - name: Upload APK to Google Drive
        run: python upload_to_drive.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcp-key.json
